server:
  port: 8085

spring:
  application:
    name: payment-service

resilience4j:
  circuitbreaker:
    instances:
      thirdPartyApi:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      thirdPartyApi:
        maxAttempts: 3
        waitDuration: 500

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
